[project]
name = "flashcards-app"
version = "0.1.0"
description = "An app to learn through flashcards and SRS"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django==6.0.4",
    "django-environ>=0.13.0",
]

[dependency-groups]
dev = [
    "djlint>=1.36.4",
    "ruff>=0.15.12",
]

[tool.djlint]
profile = "django"
indent = 2

[tool.ruff]
line-length = 120
extend-exclude = [
    "migrations",
    "flashcards_app",
    "manage.py"
]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W"]
