# Generated by Django 6.0.4 on 2026-05-05 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_text', models.CharField(max_length=70, verbose_name='Front Text')),
                ('comment', models.CharField(blank=True, max_length=120, null=True, verbose_name='Comment')),
                ('back_text', models.CharField(max_length=70, verbose_name='Back Text')),
                ('reading', models.CharField(blank=True, max_length=70, null=True, verbose_name='Reading')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Explanation')),
                ('example_text', models.TextField(blank=True, null=True, verbose_name='Example Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Datetime')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification Datetime')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.deck')),
            ],
        ),
    ]
